name: Java CI with Gradle

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ "0.0" ]
  pull_request:
    branches: [ "0.0" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # 更新为Java 21
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    - name: Setup Gradle 8.11.1
      uses: gradle/actions/setup-gradle@v4  # 更新为最新版本的动作
      with:
        gradle-version: '8.11.1'  # 指定Gradle版本为8.11.1
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle Wrapper
      run: ./gradlew assemble
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mod
        path: mod/build/libs/


  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # 更新为Java 21
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4  # 更新为最新版本的动作
